### ISSUE TITLE
500 error on board upload page

### ISSUE THREAD

**Issue by nikolas** [mcfiredrill/forttree#52]
Dang, i wanted to post this jaz drive on fortchan: ![jaz](https://cloud.githubusercontent.com/assets/59292/16429109/1ac2123a-3d43-11e6-81c3-0970c77ab632.jpg)

GET request to http://www.fortchan.org/boards/2 fails:

![2016-06-28-151456_647x209_scrot](https://cloud.githubusercontent.com/assets/59292/16429104/17202b80-3d43-11e6-9f6b-47675e6ecbcf.png)

**Comment by mcfiredrill** [comment]
Fixed now. Sorry!

**Comment by nikolas** [comment]
thanks for fixing the issue but it's back again >_<

maybe i need to dust off my heroku login and look at the logs -_-

**Comment by mcfiredrill** [comment]
2016-08-25T03:21:49.759031+00:00 app[web.1]: Aws::Errors::MissingRegionError (missing region; use :region option or export region name to ENV['AWS_REGION']):
2016-08-25T03:21:49.759032+00:00 app[web.1]:   
2016-08-25T03:21:49.759033+00:00 app[web.1]: app/models/post_form.rb:33:in `save!'
2016-08-25T03:21:49.759033+00:00 app[web.1]: app/controllers/posts_controller.rb:19:in `block in create'
2016-08-25T03:21:49.759034+00:00 app[web.1]: app/controllers/posts_controller.rb:18:in `create'
